### ISSUE TITLE
Pearson test

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#55]
Correct pearson test files using assert statements to monitr future changes

**Comment by sidhu1012** [comment]
@parva-jain Can you do it? You made that file.

**Comment by parva-jain** [comment]
> @parva-jain Can you do it? You made that file.

Ya sure!!, just like there are assert statements in random_forest_test.py. right?

**Comment by sidhu1012** [comment]
> > @parva-jain Can you do it? You made that file.
> 
> Ya sure!!, just like there are assert statements in random_forest_test.py. right?

Yes ! All Pearson functions you have used should have assert statement to check if the result obtained is the expected result or not.

**Comment by parva-jain** [comment]
Is there a necessity for assert statements after every use of functions since the corr_score function evaluates Pearson Correlation Coefficient of every feature with the target and for generating the expected result, I have to manually calculate that coefficient with a particular formula, and doing that will be time-consuming as well as lengthy. For other functions, it can be done easily.

**Comment by sidhu1012** [comment]
> Is there a necessity for assert statements after every use of functions since the corr_score function evaluates Pearson Correlation Coefficient of every feature with the target and for generating the expected result, I have to manually calculate that coefficient with a particular formula, and doing that will be time-consuming as well as lengthy. For other functions, it can be done easily.

Yes it's necessary , so that we can know that the function is working correctly.

**Comment by parva-jain** [comment]
Hey plz check out the PR associated with the issue.
